[package]
name = "sim"
version = "0.1.0"
authors = ["michaelhly <michaelhly@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.14.5"

[build-dependencies]
pyo3-build-config = "0.20.0"
